name: Daily Hidden Commit

on:
  schedule:
    - cron: '0 9 * * *'  # every day at 9:00 UTC
  workflow_dispatch:      # allows manual run

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create hidden dummy file and commit
        run: |
          echo "Daily update $(date)" >> .daily_commit.log
          git config --global user.name "andreas-tzegas"
          git config --global user.email "andreastzegas0@gmail.com"
          git add .daily_commit.log
          git commit -m "Daily automated commit $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
