name: Daily Random Commits

on:
  schedule:
    - cron: '0 0 * * *'   # triggers at 00:00 UTC (will randomize inside)
    - cron: '0 12 * * *'  # triggers at 12:00 UTC (also randomized)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Random wait before commit
        run: |
          # Generate random seconds to sleep (between 0 and 5 hours = 18000s)
          SLEEP=$(( RANDOM % 18000 ))
          echo "Sleeping $SLEEP seconds before committing..."
          sleep $SLEEP

      - name: Make hidden commit
        run: |
          echo "Update $(date)" >> .daily_commit.log
          git config --global user.name "andreas-tzegas"
          git config --global user.email "andreastzegas0@gmail.com"
          git add .daily_commit.log
          git commit -m "Random automated commit $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
