name: Daily Random Commits

permissions:
  contents: write

on:
  schedule:
    - cron: '0 9 * * *'   # 11h France (UTC+2)
    - cron: '0 17 * * *'  # 19h France
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: First commit
        run: |
          echo "Commit 1 at $(date) $RANDOM" >> .daily_commit.log
          git add .daily_commit.log
          git commit -m "chore(auto): first commit $(date)" || echo "No changes to commit"

      - name: Second commit
        run: |
          echo "Commit 2 at $(date) $RANDOM" >> .daily_commit.log
          git add .daily_commit.log
          git commit -m "chore(auto): second commit $(date)" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
